"""Added fullname attr and default manager

Revision ID: efad0d9ab39f
Revises: a93b1f1af5ae
Create Date: 2019-06-21 18:53:50.808549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efad0d9ab39f'
down_revision = 'a93b1f1af5ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=120), nullable=False))
    op.execute("insert into users (username, full_name, email, password, email_reminder, role) values ('manager', 'Manager', 'manager@gmail.com', 'pbkdf2:sha256:50000$LLVaa6vr$b9b9e5df594cc644bf5c57d9a4c7da59b8d4f42970e49835faabeae1645078a4', True, 1)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
